---
- name: Install Apache server
  hosts: node1
  become: yes
  tasks:
  - name: Lastest Apache version installed
    yum:
      name: httpd
      state: latest
  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
  - name: Copy web.html
    copy:
      src: web.html
      dest: /var/www/html/index.html